source 'https://rubygems.org'

gem 'httpclient', :require => false
gem 'trocla', '~> 0.2.3', :require => false
gem 'faraday', '< 2.0', :require => false
gem 'manticore', '>= 0.8.0', :require => false
