name: bc-compat test

on: [push, pull_request]

env:
  JRUBY_OPTS: '-J-ea -J-Djdk.tls.client.protocols="TLSv1.3,TLSv1.2"'
  MAVEN_OPTS: '-Dstyle.color=always' # force Maven colored output

# runs the Ruby suite against each supported Bouncy Castle version
jobs:

  bc-compat:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ruby-version: [ jruby-9.4.14.0, jruby-10.0.6.0 ]
        bc-version: [ '1.80', '1.81', '1.82', '1.83', '1.84', '1.85', '1.86' ]
        include:
          - ruby-version: jruby-10.0.6.0
            java-version: 21
          - ruby-version: jruby-9.4.14.0
            java-version: 11
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: bundle install
        run: bash .github/scripts/bundle-install

      - name: build jopenssl.jar
        run: jruby -rbundler/setup -S rake jar

      - name: invoker test (BC ${{ matrix.bc-version }})
        run: ./mvnw -ntp test -f src/it/${{ matrix.bc-version }}/pom.xml
        timeout-minutes: 15
