name: rake test (with provider)

on: [push, pull_request]

env:
  JAVA_TOOL_OPTIONS: >-
    -Djruby.openssl.provider.register=true
    -Djruby.openssl.log.logger=jul
    -Djruby.openssl.log.silence=false
    --add-opens=java.base/java.security=org.jruby.dist
  JRUBY_OPTS: '-J-ea -Xjit.threshold=0'

jobs:

  maven-test:
    runs-on: ubuntu-24.04 # ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ jruby-10.0.6.0 ]
        java-version: [ 21, 25 ]
        distribution: [ temurin, oracle ]
        include:
          - ruby-version: jruby-9.4.14.0
            java-version: 11
            distribution: corretto
          - ruby-version: jruby-9.4.15.0
            java-version: 21
            distribution: zulu
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}
          cache: maven

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: bundle install
        run: bash .github/scripts/bundle-install

      - name: rake test_prepare
        run: jruby -rbundler/setup -S rake test_prepare

      - name: rake test
        run: jruby -rbundler/setup -S rake test
        timeout-minutes: 15
