name: rake test

on: [push, pull_request]

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1'
  JRUBY_OPTS: '-J-ea'

jobs:

  maven-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21 ]
        ruby-version: [ jruby-9.4.5.0 ]
        include:
          - java-version: 8
            ruby-version: jruby-9.2.19.0
          - java-version: 17
            ruby-version: jruby-9.2.20.1
          - java-version: 8
            ruby-version: jruby-9.3.3.0
          - java-version: 11
            ruby-version: jruby-9.3.13.0
          - java-version: 15
            ruby-version: jruby-9.3.13.0
          - java-version: 8
            ruby-version: jruby-9.1.17.0
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: install bundler
        run: jruby -S gem install bundler -v "~>2.2.28"

      - name: bundle install
        run: jruby -S bundle install

      - name: rake test_prepare
        run: jruby -rbundler/setup -S rake test_prepare

      - name: rake test
        run: jruby -rbundler/setup -S rake test
