name: rake test

on: [push, pull_request]

env:
  JAVA_TOOL_OPTIONS: >-
    -XX:+TieredCompilation
    -XX:TieredStopAtLevel=1
    -Djruby.openssl.debug=true
  JRUBY_OPTS: '-J-ea'
  MAVEN_OPTS: '-Dstyle.color=always' # force Maven colored output

jobs:

  maven-test:
    name: ${{ matrix.runtime.ruby }} / Java ${{ matrix.runtime.java }} / ${{ matrix.test-target }}
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        runtime:
          - ruby: jruby-10.0.6.0
            java: 11
            distribution: temurin
          - ruby: jruby-10.0.6.0
            java: 21
            distribution: temurin
          - ruby: jruby-10.0.7.0
            java: 25
            distribution: temurin
          - java: 21
            distribution: oracle
            ruby: jruby-9.4.15.0
          - java: 11
            distribution: corretto
            ruby: jruby-9.4.14.0
          - java: 11
            distribution: zulu
            ruby: jruby-9.4.8.0
          - java: 11
            distribution: temurin
            ruby: jruby-9.3.13.0
          - java: 11
            distribution: temurin
            ruby: jruby-9.3.3.0
          - java: 11
            distribution: temurin
            ruby: jruby-9.2.19.0
          - java: 11
            distribution: temurin
            ruby: jruby-9.2.20.1
          - java: 24
            distribution: corretto
            ruby: jruby-10.0.5.0
          - java: 21
            distribution: oracle
            ruby: jruby-10.0.1.0
          - java: 21
            distribution: zulu
            ruby: jruby-10.1.0.0
          - java: 25
            distribution: temurin
            ruby: jruby-10.1.2.0
          - java: 21
            distribution: corretto
            ruby: jruby-head
        test-target:
          - test
          - test:provider:bc_all
          - test:provider:bc_wout_jsse
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.runtime.java }}
        uses: actions/setup-java@v6
        with:
          java-version: ${{ matrix.runtime.java }}
          distribution: ${{ matrix.runtime.distribution }}
          cache: maven

      - name: set up ${{ matrix.runtime.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.runtime.ruby }}

      - name: install bundler
        run: jruby -S gem install bundler -v "~>2.2.28"

      - name: bundle install
        run: bash .github/scripts/bundle-install

      - name: rake test_prepare
        run: jruby -rbundler/setup -S rake test_prepare

      - name: mvn test
        if: matrix.test-target == 'test'
        run: ./mvnw test

      - name: rake ${{ matrix.test-target }}
        run: jruby -rbundler/setup -S rake ${{ matrix.test-target }}
        timeout-minutes: 15
