name: rake test (with provider)

on: [push, pull_request]

env:
  JAVA_OPTS: '-Djruby.openssl.provider.register=true -Djruby.openssl.warn=true '
  JRUBY_OPTS: '-J-ea -J--add-opens=java.base/java.security=org.jruby.dist -Xjit.threshold=0'

jobs:

  maven-test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [ 11, 17 ]
        ruby-version: [ jruby-9.3.13.0 ]
        include:
          - java-version: 21
            ruby-version: jruby-9.4.5.0
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: install bundler
        run: jruby -S gem install bundler -v "~>2.2.28"

      - name: bundle install
        run: jruby -S bundle install

      - name: rake test_prepare
        run: jruby -rbundler/setup -S rake test_prepare

      - name: rake test
        run: jruby -rbundler/setup -S rake test
