name: rake test (with provider)

on: [push, pull_request]

env:
  JAVA_OPTS: '-Djruby.openssl.provider.register=true -Djruby.openssl.warn=true '
  JRUBY_OPTS: '-J-ea -J--add-opens=java.base/java.security=org.jruby.dist -Xjit.threshold=0'

jobs:

  maven-test:
    runs-on: ubuntu-24.04 # ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ jruby-9.4.8.0 ]
        java-version: [ 21, 23 ]
        distribution: [ temurin, oracle ]
        include:
          - ruby-version: jruby-9.4.8.0
            java-version: 11
            distribution: corretto
          - ruby-version: jruby-9.4.8.0
            java-version: 11
            distribution: zulu
          - ruby-version: jruby-9.4.8.0
            java-version: 11
            distribution: temurin
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.distribution }}

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: install bundler
        run: jruby -S gem install bundler -v "~>2.2.28"

      - name: bundle install
        run: jruby -S bundle install

      - name: rake test_prepare
        run: jruby -rbundler/setup -S rake test_prepare

      - name: rake test
        run: jruby -rbundler/setup -S rake test
